### ISSUE TITLE
Non-symoblic icons

### ISSUE THREAD

**Issue by bertob** [weclaw1/image-roll#1]
All the icons are non-symbolic currently, which looks very weird:

![image](https://user-images.githubusercontent.com/1908896/121746979-f7a59b80-cb06-11eb-8091-171fa57c70b0.png)

You can fix it by appending `-symbolic` to all icon names, e.g. `list-add-symbolic`.

**Comment by weclaw1** [comment]
Thank you! Merged.
The app definitely looks better with symbolic icons.
