### ISSUE TITLE
cargo install builds and runs with no arguments and opens images via the UI but doesn't work at command line

### ISSUE THREAD

**Issue by michaelmrose** [weclaw1/image-roll#11]
I am on a up to date version of Project Trident which is based on Void Linux running i3wm. I get the following error on any of several known good files

(image-roll:26676): GLib-GIO-CRITICAL **: 20:04:04.371: This application can not open files.

If I run image-roll and then use its open option I can open the same file with no issues.

**Comment by weclaw1** [comment]
Fixed in 6a3a95e50322e1b16fc8b68ccc75713053cb1dbb
Also added the ability to set Image Roll as the default program for image files.
