### ISSUE TITLE
Opens in fixed small window size

### ISSUE THREAD

**Issue by ginhiki** [weclaw1/image-roll#14]
This app always opens in a fixed small window size, even if i exit after resizing it the next time i opens it reverts back to the same small window size irrespective of what file i open. Please make it so that it remembers the last used window size. 

Using xfce with Arch. Installed the image-roll-git version from AUR.

**Comment by weclaw1** [comment]
I changed the default window size to 1024x768 as a stop gap solution. I created a new issue (#22) because saving the window size is something I want to add, but it will take some time to implement.
