### ISSUE TITLE
Make all icons real symbolics

### ISSUE THREAD

**Issue by bertob** [weclaw1/image-roll#15]
The custom icons for cropping and resizing are a bit off-style and don't recolor:

![image](https://user-images.githubusercontent.com/1908896/121791606-e7b3b780-cbeb-11eb-89f9-6d8d93794f0b.png)

I'd just use equivalent icons from [icon library](https://flathub.org/apps/details/org.gnome.design.IconLibrary), specifically `crop-symbolic` and `view-fullscreen-symbolic`.

**Comment by weclaw1** [comment]
Done in 8c075c2fd2c034c079d1ce9a535fef4730cffec1
I have used image-crop-symbolic instead of crop-symbolic because it's a system icon, so I don't have to add it to project.

**Comment by nikolowry** [comment]
@weclaw1 `image-crop-symbolic` isn't a pre-installed system icon (on Arch at least). I don't know if you'd like me to open a new issue or not.

**Broken symbolic icon:**
![Screenshot from 2021-07-09 19-42-32](https://user-images.githubusercontent.com/597310/125145402-058f1200-e0ef-11eb-86cd-8e5bc35977cc.png)

**Working symbolic icon after saving IconLibrary's to ~/.local/share/icons/image-crop-symbolic:**
![Screenshot from 2021-07-09 19-43-30](https://user-images.githubusercontent.com/597310/125145417-0fb11080-e0ef-11eb-8bea-15eadd64c89a.png)

**Comment by weclaw1** [comment]
Fixed in 610612bd4c8fd34e05eee885e737c0f607265516.
