### ISSUE TITLE
Add buttons for "zoom-to-100%" and "fit-to-page" (and even "fit-to-width")

### ISSUE THREAD

**Issue by epilys** [weclaw1/image-roll#18]
It's a helpful feature most image viewers have.

(love the tool btw kudos!)

**Comment by weclaw1** [comment]
I have added fit to screen button (fit best) in dabec000c402753f03ec5fc5ad4f194251cc7b41. I won't add zoom-to-100% because it is easy to set 100% zoom using + and - buttons, also there is not enough space for that on small screens (linux mobile phones).
