### ISSUE TITLE
Add double click to zoom action

### ISSUE THREAD

**Issue by epilys** [weclaw1/image-roll#20]

**Comment by Artturin** [comment]
the ability to scroll zoom with ctrl scrollwheel and the ability to change images with just scrolling would be nice too

**Comment by weclaw1** [comment]
I have added scroll zoom in 61b7a213227c60dd8bf34d1172271a96d5faa491. I will look into adding pinch-to-zoom today.

**Comment by weclaw1** [comment]
I have also added pinch-to-zoom. New version will be released today.
