### ISSUE TITLE
Add configurable gtk accelerators

### ISSUE THREAD

**Issue by epilys** [weclaw1/image-roll#21]
https://developer.gnome.org/gtk3/stable/gtk3-Keyboard-Accelerators.html

Some immediately useful ones:

- Ctrl-Q to quit
- Left/Right arrow keys to change image
- Ctrl+ or Ctrl- or just plain -/+ to zoom

**Comment by weclaw1** [comment]
I have added left/right arrow keys to change image and +/- to zoom in caed3e1. In order to add Ctrl-Q to quit I will have to add GActions to the applications, so that will come later.

**Comment by weclaw1** [comment]
I have added Ctrl-Q to quit in cb46dd220e89e759a90f04bd12be5d69abbcc063.
