### ISSUE TITLE
Confirmation before file deletion

### ISSUE THREAD

**Issue by etnadji** [weclaw1/image-roll#26]
Hi,

As the delete button is close from Image Roll menu button, it might be a good idea to add a confirmation dialog before the deletion.
Of course, if you want to delete a lot of files, it could be annoying, but less than loosing a file by accident.

Also, it could be a good idea to apply the "destructive-action" style class to the delete button.

[sorry for the possible broken english]

**Comment by weclaw1** [comment]
Deletion moves files to trash which should prevent loosing a file by accident :)

**Comment by etnadji** [comment]
Ah, my bad :)

**Comment by teackot** [comment]
But it's still not obvious. I think you should use an in-app notification saying that file was moved to trash, maybe with a cancel button

"Удалён объект b" ("object b was removed")

![image](https://user-images.githubusercontent.com/85305327/149788740-cce7f034-d05e-48ef-92d5-2e5741a041ff.png)

**Comment by weclaw1** [comment]
Notification is a good idea, I will add this.

**Comment by weclaw1** [comment]
Fixed in 08befab31d10e5a0f59e3910c4340da94d378de7
