### ISSUE TITLE
Process keeps running in background

### ISSUE THREAD

**Issue by MichaelMcDonnell** [weclaw1/image-roll#32]
The `image-roll` process keeps running in the background after I close the window. It only happens if I use the open menu. It doesn't keep running in the background if I use the command-line to open an image or if I double-click on an image.

If I run the version compiled from source then the process is at least alive after 10 minutes (I manually ended the process after that).

The flatpak version does end the process eventually after 40 seconds. I suspect `bwrap` or something else external ends the process.

Operating system: Fedora 35
Version: Flatpak 1.3.1 and debug main 5dc0253e145257026b9fb3cd89b1d9bc8ebe028a

Steps to reproduce:

1. Open Image Roll from the menu or from the command-line (do not double-click an image).
2. Click the hamburger menu button and click "Open...".
3. Select an image and click "Select".
4. Click the X to close the window.
5. Open a terminal and run `ps -aux | grep image-roll`
6. Notice that the `image-roll` process is still running.

Again, the flatpak version seems to eventually stop after 40 seconds but a version compile from source doesn't seem to ever stop.

Thanks for writing a Rust image app by the way! I'm excited to be able to run more Rust  code for daily tasks :smile:

**Comment by MichaelMcDonnell** [comment]
If I move the `file_chooser.destroy()` call out of signal handler then the bug goes away. I don't understand why. If the destroy call is not queued then it might be destroying something that is still being used, which would result in undefined behavior. Either way, it is fine to destroy it after the `file_chooser.run()` call because it "blocks" (it enters a recursive main loop more specifically [1]). That would be the simplest solution:

```rust
file_chooser.connect_response(move |file_chooser, response| {
    if response == gtk::ResponseType::Accept {
        let file = if let Some(file) = file_chooser.file() {
            file
        } else {
            post_event(&sender, Event::DisplayError(anyhow!("Couldn't load file")));
            return;
        };
        post_event(&sender, Event::OpenFile(file));
    }
});

file_chooser.run();
file_chooser.destroy();
```

Another option is to not use a signal handler. The code already "blocks" on the `file_chooser.run()` call:

```rust
if file_chooser.run() == gtk::ResponseType::Accept {
    let file = if let Some(file) = file_chooser.file() {
        file
    } else {
        post_event(&sender, Event::DisplayError(anyhow!("Couldn't load file")));
        return;
    };
    post_event(&sender, Event::OpenFile(file));
}

file_chooser.destroy();
```

[1] [https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/prelude/trait.NativeDialogExt.html#tymethod.run](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/prelude/trait.NativeDialogExt.html#tymethod.run)

**Comment by weclaw1** [comment]
I think that the file chooser is not fully destroyed when it runs in the signal handler, most likely that "zombie" file chooser keeps the app open after closing the window.

**Comment by weclaw1** [comment]
I have merged your commit, I have also found similar problem in save as file chooser dialog which will be fixed in another commit.

**Comment by MichaelMcDonnell** [comment]
Yeah that sounds plausible. Thanks!
