### ISSUE TITLE
Guess file type on magic byte instead of filename extension

### ISSUE THREAD

**Issue by SecT0uch** [weclaw1/image-roll#34]
First off, thanks for your work. This app looks promising!

Would it be possible to get the media type based on the magic byte and not the filename ?
I got a few images without file extension and image-roll fails to read it:
`ERROR: Couldn't find /path/to/file in enumerated files`

I think this is the relevant line:
https://github.com/weclaw1/image-roll/blob/8505b9f22abb5cce1747282b8cbd9a12c4c2376d/src/file_list.rs#L147

I have no experience with Rust, but from what I understand, we should feed `Gio.content_type_guess` with the image data? 

Source: https://lazka.github.io/pgi-docs/Gio-2.0/functions.html#Gio.content_type_guess

**Comment by weclaw1** [comment]
Fixed in ffb1456f377acfe93b3cb5148ccae0ab045931cb :)
With this change I also fixed opening images on network shares.
