### ISSUE TITLE
[Feature Request] Full-screen mode

### ISSUE THREAD

**Issue by edo0** [weclaw1/image-roll#38]
First of all, thank you very much for your work on image roll!!
I was wondering if it would be possible to add a full-screen mode, triggered by:
- a classical F11
- or even better, a double click on the image.

Thank you for taking your time reading this.

**Comment by weclaw1** [comment]
I have added fullscreen mode in cb46dd220e89e759a90f04bd12be5d69abbcc063. You can activate it by pressing F11.

**Comment by edo0** [comment]
@weclaw1 Thank you for weighing in on this.
Unfortunately on my system (elementary os 6.1, built atop of Ubuntu 20.04.3) pressing F11 will not sort any effect.

**Comment by weclaw1** [comment]
@edo0 I have just added this change, you will have to wait for a new version to be released in order to use it.
I will probably release a new version today. I'll write a comment here when I do.

**Comment by edo0** [comment]
Thank you very much!

**Comment by weclaw1** [comment]
The new version is released.
Please update to 1.5.0 and try again :)

**Comment by edo0** [comment]
Works like a charm, thank you very much!!
