### ISSUE TITLE
Test failed on s390x

### ISSUE THREAD

**Issue by remilauzier** [weclaw1/image-roll#40]
https://kojipkgs.fedoraproject.org/work/tasks/8709/83278709/build.log
it's possible that the failure is done because of the endianess of s390x.
Can't test the version 1.6 for now since ashpd is not package in fedora for now.

failures:
---- image_list::tests::save_current_image_overwrites_image_at_current_image_path_when_filename_is_set_to_none stdout ----
thread 'image_list::tests::save_current_image_overwrites_image_at_current_image_path_when_filename_is_set_to_none' panicked at 'assertion failed: modification_date > creation_date', src/image_list.rs:159:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    image_list::tests::save_current_image_overwrites_image_at_current_image_path_when_filename_is_set_to_none
test result: FAILED. 31 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s

**Comment by weclaw1** [comment]
Some file systems don't store creation time, maybe this error is because of that?
I used modified time for test file creation time in aece852b16a76f68e67b1fbbb764e05a8026294d.
Could you change created() to modified() in this test on 1.5 and run it again in order to check if this fixes it?

**Comment by remilauzier** [comment]
Will see if i can test it. But the file system use by koji should be the same between all architecture if i remember correctly.

**Comment by remilauzier** [comment]
Not sure if koji as been having some problem but now it seem that ppc64le is having problem with test.
They seem to failed to completed before sixty seconds. S390x seem to be fix by the change.
https://kojipkgs.fedoraproject.org//work/tasks/5195/83285195/build.log

**Comment by remilauzier** [comment]
It was a temporary bug in koji. test passed on ppc64le too. the patch fix the problem on s390x. Thanks!
