### ISSUE TITLE
[Feature] Implementing a shortcut for quitting the application

### ISSUE THREAD

**Issue by edo0** [weclaw1/image-roll#42]
As per the title, I think a shortcut to quit would be rather convenient.

I would propose to follow the mpv standard, so using lowercase "q" to quit the viewer. 
(along the same line, an alternative way of implementing full screen could be "f", I hope you can consider it as a possibility)

Thank you for your time!

**Comment by weclaw1** [comment]
In the latest version you can use the shortcut CTRL+q to quit the application
