### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by chri2** [weclaw1/image-roll#44]
debian package image-roll 1.6.0 running on PureOS byzantium (debian derivate)

When zoom mode is adopt to the window size and a picture large enough to be scaled down is loaded the cpu usage rises very high (and on my notebook the fan starts going mad which it doesn't do on any other occasion except compiling).

**Comment by weclaw1** [comment]
I have just released a new version which should improve the performance. Please update and let me know if the cpu usage is okay now.
