### ISSUE TITLE
An AUR page?

### ISSUE THREAD

**Issue by Kommynct** [weclaw1/image-roll#7]
I would love it if this was added to the AUR, i've been searching for a good image viewer for forever, and this seems perfect.

**Comment by ThatOneCalculator** [comment]
It already is, `image-roll`, `image-roll-bin` and `image-roll-git`. Did you even bother to do a simple `yay -Ss image-roll`? 

![image](https://user-images.githubusercontent.com/44733677/121762056-76d7a700-cae8-11eb-8455-195bd94c2abf.png)

**Comment by Kommynct** [comment]
No, i'm stupid and googled it and saw no relevant results, sorry about this.
